name: Build and publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
          cache: 'gradle'
      - name: Prepare older versions
        run: |
          rm -rf build/dokka/versioned
          git clone -b gh-pages https://github.com/lusory/kframe.git build/dokka/versioned || true
          rm -rf build/dokka/versioned/.git
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew publish dokkaHtmlMultiModule
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: build/dokka/versioned
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          commit-message: 'docs: update with ${{ github.sha }}'